name: Feature Request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement"]
assignees: []

body:
  - type: textarea
    id: motivations
    attributes:
      label: Motivations
      description: If your feature request is related to a problem, please describe it.
    validations:
      required: true

  - type: dropdown
    id: implement-feature
    attributes:
      label: Would you like to implement this feature?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Describe the solution you'd like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
